### ISSUE TITLE
API Key listed publicly

### ISSUE THREAD

**Issue by cdloh** [AdityaHegde/track-dota#1]
Hey mate,

I'd recommend not leaving your API Key in that config file there. Anybody could grab that and abuse it and get your APIKey banned.

It's listed [here](https://github.com/AdityaHegde/track-dota/blob/master/app/config/config.js).

**Comment by AdityaHegde** [comment]
Thanks dude. I had forgotten to add that file to .gitignore. Will have to recreate the api key.
